### ISSUE TITLE
No redirects on HTTPS

### ISSUE THREAD

**Issue by Minoru** [yesodweb/yesodweb.com#26]
This is an infrastructure issue, not code issue, but I don't know a better place to report it.

http://yesodweb.com (non-secure HTTP) redirects to http://www.yesodweb.com (non-secure HTTP), but https://yesodweb.com (secure HTTP) doesn't redirect anywhere. This confused me for a moment when I manually typed the HTTPS URL and got "Unable to connect" error. All roads should lead to Rome :)

I suspect [this line in keter.yml](https://github.com/yesodweb/yesodweb.com/blob/c3a0eaacab9377fdaa734d2776815d77210ffd13/config/keter.yaml-#L23) should be changed to "443", but I couldn't verify that because I don't have Keter installed and the docs are hard to come by (I ended up reading Keter.Types.V10 instead).

**Comment by snoyberg** [comment]
Thanks for the heads-up. I've changed the bare domain forwarding to use an A-record, which allows for proper certificates to be served. The redirect should be working now.

**Comment by Minoru** [comment]
Accessing https://yesod.com, I'm still getting an error, albeit a new one:

```
yesod.com uses an invalid security certificate.

The certificate is only valid for the following names:
  oasis.aqhostdns.com, www.oasis.aqhostdns.com

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

The quote is from Firefox 58.0.2 on Linux, but I'm seeing effectively the same in Chromium 64.0.3282.167.

**Comment by snoyberg** [comment]
Unfortunately I don't control that domain name.

**Comment by Minoru** [comment]
Oh! Sorry, that was a typo. Accessing https://yesodweb.com redirects as it should. Thank you!
